---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_IP: 10.24.0.200
  METALLB_LB_RANGE: 10.24.0.210-10.24.0.249
  # INGRESS_NGINX_LB: 10.24.0.210
  LB_JELLYFIN_IP: 10.24.0.211
  LB_VECTOR_IP: 10.24.0.212
  LB_PLEX_IP: 10.24.0.213
  LB_OMADA_IP: 10.24.0.214
  LB_ISTIO_INGRESS_GATEWAY: 10.24.0.215
  LB_GITEA_IP: 10.24.0.216
  LB_HOME_ASSISTANT_IP: 10.24.0.217
  LB_UNIFI_IP: 10.24.0.218
  LB_MOSQUITTO_IP: 10.24.0.219
  LB_TRAEFIK_IP: 10.24.0.220
  LB_VCLUSTER_IP: 10.24.0.221
  LB_ISTIO_PASSTHRU_GATEWAY: 10.24.0.222
  LB_NUT_V4: 10.24.0.223
  LB_COREDNS_IP: 10.24.0.225
  LB_PROMTAIL_IP: 10.24.0.226