apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bitnami-charts.yaml
- ingress-nginx-charts.yaml
- jetstack-charts.yaml
- k8s-at-home-charts.yaml
- metallb-charts.yaml
- longhorn-charts.yaml
- authentik-charts.yaml
- traefik-charts.yaml
- hajimari-charts.yaml
- node-feature-discovery-charts.yaml
- rook-ceph-charts.yaml
- weaveworks-kured-charts.yaml
- grafana-charts.yaml
- prometheus-community-charts.yaml
- stakater-charts.yaml
- minio-charts.yaml
- metrics-server-charts.yaml
- external-dns-charts.yaml
- vmware-tanzu-charts.yaml