apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - istio-base/ks.yaml
  - istio-cni/ks.yaml
  - istiod/ks.yaml
  - istio-ingress
  - observability
  - virtual-services