---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s-helm-charts
  namespace: flux-system
spec:
  interval: 1h
  url: http://bjw-s.github.io/helm-charts/
  timeout: 3m
