apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack
  - grafana
  # - speedtest-exporter
  - thanos
  # - network-ups-tools/ks.yaml
  # - loki/secret.sops.yaml
  # - loki/ks.yaml
  # - vector/ks.yaml
