apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-system
  - networking
  - security
  - media
  - monitoring
  - rook-ceph
  - development
  - home
  - kopia
  # - debug
  - kyverno/ks.yaml
  # - neuvector
  # - sso
