apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.yaml
- metallb-system.yaml
- networking.yaml
- security.yaml
- media.yaml
- rook-ceph.yaml
- monitoring.yaml
- cattle-system.yaml
- development.yaml
- home.yaml
- kasten-io.yaml
- system-upgrade.yaml
